### ISSUE TITLE
In-browser NAT traversal via js-libp2p-circuit

### ISSUE THREAD

**Issue by davepuchyr** [libp2p/js-libp2p-circuit#32]
Hi, @jacobheun,

Would you be so kind as to add an in-browser example for js-libp2p-circuit similar to https://github.com/libp2p/js-libp2p/tree/master/examples/libp2p-in-the-browser?  I have a libp2p dependent app that works perfectly when the (browser) nodes have public ip addresses, but fails when NAT is involved and I can't figure out how to incorporate js-libp2p-circuit in the mix.

Kind regards,

Dave

**Comment by jacobheun** [comment]
Hi @davepuchyr! Yes, we do need to get an example together for circuit relay with better description of what the configuration options do.

Currently libp2p-circuit is turned on in libp2p-switch via configuration of libp2p. In the browser example, you should be able to do this by enabling the relay config at https://github.com/libp2p/js-libp2p/blob/v0.23.1/examples/libp2p-in-the-browser/1/src/browser-bundle.js#L62-L68. There you can enabled the relay itself, and hop.

**Comment by jacobheun** [comment]
Circuit Relay does support stop. 

Are you using a relay node in between the browser and headless node? Without knowing more about your setup it sounds like the NATed node is trying to dial the headless node directly. Is the headless node the relay, or the destination node? If you're solely using webrtc transports it should be helping with NAT piercing. Do you have your code up anywhere? What kind of errors are you seeing if any?

In regards to general NAT efforts, we are still working on other nat traversal options, https://github.com/libp2p/js-libp2p/issues/104. It's on the todo list, but isn't our highest priority currently so it may be some time.

**Comment by davepuchyr** [comment]
There's no relay node between the browser and headless node.  The browser is directly dialing the headless node and the headless node is the destination.  The error I get is 

`Error: Circuit not enabled and all transports failed to dial peer Qm...SHQe1!
   at i (https://win.in3s.com/js/vendor.434131d.js:78:75119)
   at switch.transport.dial (https://win.in3s.com/js/vendor.434131d.js:78:75410)
   at dialer.dialMany (https://win.in3s.com/js/vendor.434131d.js:72:139935) 
   at ...`

The code base is already large, so wouldn't be of much help.  I will try to reproduce the error with minimal example code.  

The part that I can't wrap my head around is that the browser node is doing the dialing but it seems that it is the headless node that tries to open the connection (and fails).  Does that make any sense to you?  (The system does work when NAT isn't involved.)

**Comment by davepuchyr** [comment]
It turns out that my problem was due to the headless node being in a docker container and had nothing to do with relaying.  I'm still interested in relaying and would love to see an example, but I know that everyone's time is precious.

Thanks for your help, @jacobheun.

**Comment by dryajov** [comment]
Hey @davepuchyr, here is a tutorial (https://github.com/ipfs/js-ipfs/blob/master/examples/circuit-relaying/README.md) on how to set up circuit relaying for both go and js. I believe this should explain most of the steps involved.

**Comment by dryajov** [comment]
@davepuchyr happy to help in any case :)
